# generated by datamodel-codegen:
#   filename:  en.yaml
#   timestamp: 2026-08-20T10:40:43+00:00

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LongName:
    train_from: str
    train_via: str


@dataclass
class Channel:
    long_name: LongName
    short_name: str


@dataclass
class Footer:
    notice: str


@dataclass
class Info:
    description: str
    via: str
    via_and: str
    next_stop: str


@dataclass
class EndOfConnection:
    message: str


@dataclass
class Announcement:
    title: str
    end_of_connection: EndOfConnection


@dataclass
class Embeds:
    footer: Footer
    info: Info
    announcement: Announcement


@dataclass
class RichPresence:
    arrival: str


@dataclass
class Model:
    channel: Channel
    embeds: Embeds
    rich_presence: RichPresence
